### ISSUE TITLE
LivePage does not reload the page

### ISSUE THREAD

**Issue by megasan84** [MikeRogers0/LivePage#102]
LivePage used to work, but now Livepage stopped automatically reloading the page.
When I click the F5 on page, page is updated.
The page is on localhost

OS: Archlinux
Browser: Google Chrome 54.0.2840.90 (64-bit)

**Comment by MikeRogers0** [comment]
Thanks for reporting this @megasan84, I'm struggling to reproduce this though I'm seeing other reports of people mentioning the issue.

I'm looking into this now :)

**Comment by MikeRogers0** [comment]
I've pushed a patch to the Chrome Store ( 2.6.1 ), it should solve your issue. If not could you do the following:

In this ticket, share what your current LivePage options are set to, the full URL (e.g. https://localhost:8080/myfile.html ) and any console output.

Thanks :)

**Comment by megasan84** [comment]
Version 2.6.1 did not help me solve the problem.
My page does not open directly.
I have my own small MVC engine, which loads the content from the template.
Previously, everything worked, now no.

**Comment by MikeRogers0** [comment]
I appreciate you're patience while I fix this bug. I just pushed another hotfix ( 2.6.2 ) to the store. If you could report back if this fixes I'll be very appreciative! 

I think the issue was with https://github.com/MikeRogers0/LivePage/blob/886167a8b3dd120e23a7b908b3ce7f549f58e068/js/injected/livepage.js#L220 this line of code.

**Comment by megasan84** [comment]
The expansion version in the store remained 2.6.1 :(

**Comment by megasan84** [comment]
Sorry, but version 2.6.2 not resolved my problem :(

**Comment by MikeRogers0** [comment]
@megasan84 I'm not certain how to fix.

If you're feeling confident could you debug your end?

https://github.com/MikeRogers0/LivePage#running-development-version-in-chrome - How to get setup locally.
https://github.com/MikeRogers0/LivePage/blob/master/js/injected/livepage.js#L206 - The method changed in the last update.

Thank you!

**Comment by megasan84** [comment]
I installed extension from git.
Directly file index.html from the demo folder works, that is, the update happens.
But on my project still does not work :(

**Comment by MikeRogers0** [comment]
@megasan84 Do you have a version of the project I can run my end to debug?
